version: 2.1
jobs:
  bygg:
    docker:
    - image: circleci/openjdk:11
    steps:
    - checkout
    - restore_cache:
        keys:
          - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          - maven-repo-v1-{{ .Branch }}-
          - maven-repo-v1-
    - run:
          name: Bygger med Maven
          command: mvn clean package
    - save_cache:
        paths:
          - ~/.m2
        key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
    - setup_remote_docker
    - run:
        name: Bygger Docker image
        command: docker build -t "navikt/sykefravarsstatistikk-api:$CIRCLE_SHA1" .
    - run:
        name: Pusher Docker image
        command: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
          docker push "navikt/sykefravarsstatistikk-api:$CIRCLE_SHA1"
          echo "Docker image: $CIRCLE_SHA1"

  deploy-til-dev:
    docker:
      - image: 'navikt/deployment-cli:v0.1.6'
    steps:
      - deploy:
          cluster: "dev-fss"
          nais-yaml: "dev-nais.yaml"


commands:
  deploy:
    description: Deploy til et gitt milj√∏
    parameters:
      cluster:
        type: string
      nais-yaml:
        type: string
    steps:
      - checkout
      - run:
          name: Deploy til << parameters.cluster >>
          command: deployment-cli deploy create --cluster=<< parameters.cluster >> --repository=navikt/sykefravarsstatistikk-api --team=teamtag --resource=<< parameters.nais-yaml >> --version=$CIRCLE_SHA1 --ref=$CIRCLE_BRANCH

workflows:
  version: 2.1
  bygg_og_deploy:
    jobs:
      - bygg:
          context: NAIS deployment
      - deploy-til-dev:
          requires:
            - bygg
          filters:
            branches:
              only:
                - master

